### ISSUE TITLE
Multi-Protocol Reach NLRI from Juniper causes a crash

### ISSUE THREAD

**Issue by fincham** [faucetsdn/beka#9]
Hello hello,

Parsing this message:

```
20:57:20.386957 IP6 (class 0xc0, flowlabel 0x5e6ef, hlim 1, next-header TCP (6) payload length: 136) 2404:138:134:120::1.58823 > 2404:138:134:120::2.179: Flags [P.], cksum 0x96aa (correct), seq 64:168, ack 63, win 17074, options [nop,nop,TS val 2962291451 ecr 242517267], length 104: BGP
	Keepalive Message (4), length: 19
	Update Message (2), length: 85
	  Origin (1), length: 1, Flags [T]: IGP
	    0x0000:  00
	  AS Path (2), length: 6, Flags [T]: 38022 
	    0x0000:  0201 0000 9486
	  Community (8), length: 4, Flags [OT]: 38022:10700
	    0x0000:  9486 29cc
	  Multi-Protocol Reach NLRI (14), length: 38, Flags [OE]: 
	    AFI: IPv6 (2), SAFI: Unicast (1)
	    nexthop: 2404:138:134:120::1, fe80::f21c:2dff:fe7f:a796, nh-length: 32, no SNPA
	      ::/0
	    0x0000:  0002 0120 2404 0138 0134 0120 0000 0000
	    0x0010:  0000 0001 fe80 0000 0000 0000 f21c 2dff
	    0x0020:  fe7f a796 0000
```

Which looks like this on the wire:

```
0000   90 0e 00 26 00 02 01 20 24 04 01 38 01 34 01 20  ...&... $..8.4. 
0010   00 00 00 00 00 00 00 01 fe 80 00 00 00 00 00 00  ................
0020   f2 1c 2d ff fe 7f a7 96 00 00                    ..-.......
```

Causes a crash on line 317 in bgp_message.py, because during

```
afi, safi, next_hop_length = struct.unpack("!HBB", stream.read(4))
```

The BytesIO object is being created from an empty string. Tracking it back a little bit I have found that in parse_path_attributes the packed_attribute being passed in is just '\x00', which seems wrong.

I ran out of time tonight, but I can have another poke at this later. v4 is working with Juniper OK, from what I can tell.

**Comment by samrussell** [comment]
Nice find! My guess is that it's because we're not supporting the extended length bit (we ignore all the flags which is a little naughty), first byte is 0x90 = 0x80 | 0x10 - this means we have a uint16 for length (0x0026) instead of uint8 (default behaviour) - so we're just reading the first octet and getting 0.

Seems weird that juniper is using this - it's technically part of the standard, but the size is well short of 256 bytes.

I've pushed a workaround to master, can you let me know if this fixes it?
